-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity DIG_JK_FF_AS is
  generic (Default : std_logic);  
  port (
    Q: out std_logic;
    notQ: out std_logic;
    Set: in std_logic;
    J: in std_logic;
    C: in std_logic;
    K: in std_logic;
    Clr: in std_logic );
end DIG_JK_FF_AS;

architecture Behavioral of DIG_JK_FF_AS is
  signal state: std_logic := Default;
begin
    process (C, Clr, Set)
    begin
        if (Set='1') then
            state <= '1';
        elsif (Clr='1') then
            state <= '0';
        elsif rising_edge(C) then
          if (J='0' and K='1') then
             state <= '0';
          elsif (J='1' and K='0') then
             state <= '1';
          elsif (J='1' and K='1') then
             state <= not (state);
          end if;
        end if;
    end process;

    Q <= state;
    notQ <= NOT( state );
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

-- Synchronous 4-Bit Up/Down Binary Counter with Dual Clock
entity n74193 is
  port (
    DN: in std_logic; -- Down Count
    UP: in std_logic; -- Up Count
    D0: in std_logic; -- Data Input 0
    D1: in std_logic; -- Data Input 1
    D2: in std_logic; -- Data Input 2
    D3: in std_logic; -- Data Input 3
    CLR: in std_logic; -- Clear
    notLD: in std_logic; -- Load
    VCC: in std_logic;
    GND: in std_logic;
    notBO: out std_logic; -- Borrow Output
    notCO: out std_logic; -- Carry Output
    Q0: out std_logic; -- Output Q0
    Q1: out std_logic; -- Output Q1
    Q2: out std_logic; -- Output Q2
    Q3: out std_logic -- Output Q3
    );
end n74193;

architecture Behavioral of n74193 is
  signal Q0_temp: std_logic;
  signal Q1_temp: std_logic;
  signal Q2_temp: std_logic;
  signal Q3_temp: std_logic;
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal s15: std_logic;
  signal s16: std_logic;
  signal s17: std_logic;
  signal s18: std_logic;
  signal s19: std_logic;
  signal s20: std_logic;
  signal s21: std_logic;
  signal s22: std_logic;
  signal s23: std_logic;
begin
  s1 <= NOT DN;
  s0 <= NOT UP;
  s7 <= NOT CLR;
  s6 <= NOT notLD;
  s8 <= NOT (D0 AND s6 AND s7);
  s11 <= NOT (s1 OR s0);
  s12 <= NOT (D1 AND s6 AND s7);
  s16 <= NOT (D2 AND s6 AND s7);
  s20 <= NOT (D3 AND s6 AND s7);
  s9 <= (NOT s7 OR NOT (NOT (s8 AND s6)));
  s10 <= NOT s8;
  s13 <= (NOT s7 OR NOT (NOT (s12 AND s6)));
  s14 <= NOT s12;
  s17 <= (NOT s7 OR NOT (NOT (s16 AND s6)));
  s18 <= NOT s16;
  s21 <= (NOT s7 OR NOT (NOT (s20 AND s6)));
  s22 <= NOT s20;
  gate0: entity work.DIG_JK_FF_AS
    generic map (
      Default => '0')
    port map (
      Set => s10,
      J => '1',
      C => s11,
      K => '1',
      Clr => s9,
      Q => Q0_temp,
      notQ => s2);
  s15 <= NOT ((s1 AND s2) OR (Q0_temp AND s0));
  gate1: entity work.DIG_JK_FF_AS
    generic map (
      Default => '0')
    port map (
      Set => s14,
      J => '1',
      C => s15,
      K => '1',
      Clr => s13,
      Q => Q1_temp,
      notQ => s3);
  s19 <= NOT ((s1 AND s2 AND s3) OR (Q0_temp AND Q1_temp AND s0));
  gate2: entity work.DIG_JK_FF_AS
    generic map (
      Default => '0')
    port map (
      Set => s18,
      J => '1',
      C => s19,
      K => '1',
      Clr => s17,
      Q => Q2_temp,
      notQ => s4);
  s23 <= NOT ((s1 AND s2 AND s3 AND s4) OR (Q0_temp AND Q1_temp AND Q2_temp AND s0));
  gate3: entity work.DIG_JK_FF_AS
    generic map (
      Default => '0')
    port map (
      Set => s22,
      J => '1',
      C => s23,
      K => '1',
      Clr => s21,
      Q => Q3_temp,
      notQ => s5);
  notCO <= NOT (Q0_temp AND Q1_temp AND Q2_temp AND Q3_temp AND s0);
  notBO <= NOT (s1 AND s2 AND s3 AND s4 AND s5);
  Q0 <= Q0_temp;
  Q1 <= Q1_temp;
  Q2 <= Q2_temp;
  Q3 <= Q3_temp;
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;

entity DIG_Add is
  generic ( Bits: integer ); 
  port (
    s: out std_logic_vector((Bits-1) downto 0);
    c_o: out std_logic;
    a: in std_logic_vector((Bits-1) downto 0);
    b: in std_logic_vector((Bits-1) downto 0);
    c_i: in std_logic );
end DIG_Add;

architecture Behavioral of DIG_Add is
   signal temp : std_logic_vector(Bits downto 0);
begin
   temp <= ('0' & a) + b + c_i;

   s    <= temp((Bits-1) downto 0);
   c_o  <= temp(Bits);
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

-- 4-bit binary full adder, alternative pinning
entity n74283 is
  port (
    C0: in std_logic;
    B1: in std_logic;
    B2: in std_logic;
    B3: in std_logic;
    B4: in std_logic;
    A1: in std_logic;
    A2: in std_logic;
    A3: in std_logic;
    A4: in std_logic;
    VCC: in std_logic;
    GND: in std_logic;
    S1: out std_logic;
    S2: out std_logic;
    S3: out std_logic;
    S4: out std_logic;
    C4: out std_logic);
end n74283;

architecture Behavioral of n74283 is
  signal s0: std_logic_vector(3 downto 0);
  signal s5: std_logic_vector(3 downto 0);
  signal s6: std_logic_vector(3 downto 0);
begin
  s5(0) <= B1;
  s5(1) <= B2;
  s5(2) <= B3;
  s5(3) <= B4;
  s0(0) <= A1;
  s0(1) <= A2;
  s0(2) <= A3;
  s0(3) <= A4;
  gate0: entity work.DIG_Add
    generic map (
      Bits => 4)
    port map (
      a => s0,
      b => s5,
      c_i => C0,
      s => s6,
      c_o => C4);
  S1 <= s6(0);
  S2 <= s6(1);
  S3 <= s6(2);
  S4 <= s6(3);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

-- 4-bit comparator
entity n7485 is
  port (
    PleQ_i: in std_logic;
    PeqQ_i: in std_logic;
    PgrQ_i: in std_logic;
    P_0: in std_logic;
    P_1: in std_logic;
    P_2: in std_logic;
    P_3: in std_logic;
    Q_0: in std_logic;
    Q_1: in std_logic;
    Q_2: in std_logic;
    Q_3: in std_logic;
    VCC: in std_logic;
    GND: in std_logic;
    PleQ: out std_logic;
    PeqQ: out std_logic;
    PgrQ: out std_logic);
end n7485;

architecture Behavioral of n7485 is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
begin
  s0 <= NOT (P_0 AND Q_0);
  s2 <= NOT (P_1 AND Q_1);
  s4 <= NOT (P_2 AND Q_2);
  s6 <= NOT (P_3 AND Q_3);
  s1 <= NOT ((P_0 AND s0) OR (s0 AND Q_0));
  s3 <= NOT ((P_1 AND s2) OR (s2 AND Q_1));
  s5 <= NOT ((P_2 AND s4) OR (s4 AND Q_2));
  s7 <= NOT ((P_3 AND s6) OR (s6 AND Q_3));
  PgrQ <= (NOT (Q_3 AND s6) AND NOT (Q_2 AND s4 AND s7) AND NOT (Q_1 AND s2 AND s7 AND s5) AND NOT (Q_0 AND s0 AND s7 AND s5 AND s3) AND NOT (s7 AND s5 AND s3 AND s1 AND PleQ_i) AND NOT (s7 AND s5 AND s3 AND s1 AND PeqQ_i));
  PeqQ <= (s7 AND s5 AND PeqQ_i AND s3 AND s1);
  PleQ <= (NOT (PeqQ_i AND s1 AND s3 AND s5 AND s7) AND NOT (PgrQ_i AND s1 AND s5 AND s3 AND s7) AND NOT (s3 AND s5 AND s7 AND s0 AND P_0) AND NOT (s5 AND s7 AND s2 AND P_1) AND NOT (s7 AND s4 AND P_2) AND NOT (s6 AND P_3));
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_BUS_1 is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic;
    
    in_0: in std_logic_vector ((Bits-1) downto 0);
    in_1: in std_logic_vector ((Bits-1) downto 0) );
end MUX_GATE_BUS_1;

architecture Behavioral of MUX_GATE_BUS_1 is
begin
  with sel select
    p_out <=
      in_0 when '0',
      in_1 when '1',
      (others => '0') when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
use ieee.numeric_std.all;
entity DIG_D_FF_BUS is
  generic (
    Default: integer; 
    Bits: integer );
  port ( D  : in std_logic_vector ((Bits-1) downto 0);
         C  : in std_logic;
         Q  : out std_logic_vector ((Bits-1) downto 0);
         notQ : out std_logic_vector ((Bits-1) downto 0) );
end DIG_D_FF_BUS;

architecture Behavioral of DIG_D_FF_BUS is
   signal state : std_logic_vector ((Bits-1) downto 0) := std_logic_vector(to_unsigned(Default, Bits));
begin
   Q    <= state;
   notQ <= NOT( state );

   process(C)
   begin
      if rising_edge(C) then
        state  <= D;
      end if;
   end process;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

-- hex synchronous counter
entity n74163 is
  port (
    notPE: in std_logic;
    notSR: in std_logic;
    CP: in std_logic;
    CET: in std_logic;
    CEP: in std_logic;
    P0: in std_logic;
    P1: in std_logic;
    P2: in std_logic;
    P3: in std_logic;
    VCC: in std_logic;
    GND: in std_logic;
    TC: out std_logic;
    Q0: out std_logic;
    Q1: out std_logic;
    Q2: out std_logic;
    Q3: out std_logic);
end n74163;

architecture Behavioral of n74163 is
  signal s0: std_logic_vector(3 downto 0);
  signal s1: std_logic_vector(3 downto 0);
  signal s2: std_logic_vector(3 downto 0);
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic_vector(3 downto 0);
  signal s6: std_logic_vector(3 downto 0);
  signal s7: std_logic_vector(3 downto 0);
begin
  s4 <= (CEP AND CET);
  s6(0) <= P0;
  s6(1) <= P1;
  s6(2) <= P2;
  s6(3) <= P3;
  gate0: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 4)
    port map (
      sel => s4,
      in_0 => s1,
      in_1 => s2,
      p_out => s5);
  TC <= (s3 AND CET);
  gate1: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 4)
    port map (
      sel => notPE,
      in_0 => s6,
      in_1 => s5,
      p_out => s7);
  gate2: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 4)
    port map (
      sel => notSR,
      in_0 => "0000",
      in_1 => s7,
      p_out => s0);
  gate3: entity work.DIG_D_FF_BUS -- Q
    generic map (
      Default => 0,
      Bits => 4)
    port map (
      D => s0,
      C => CP,
      Q => s1);
  gate4: entity work.DIG_Add
    generic map (
      Bits => 4)
    port map (
      a => s1,
      b => "0001",
      c_i => '0',
      s => s2,
      c_o => s3);
  Q0 <= s1(0);
  Q1 <= s1(1);
  Q2 <= s1(2);
  Q3 <= s1(3);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    paddle_down: in std_logic;
    paddle_up: in std_logic;
    paddle_load_n: in std_logic;
    paddle_clear: in std_logic;
    paddle_q2_in: in std_logic;
    paddle_q3_in: in std_logic;
    paddle_q1_in: in std_logic;
    paddle_q0_in: in std_logic;
    pixel_clock: in std_logic;
    paddle_d0: out std_logic;
    paddle_d1: out std_logic;
    paddle_d2: out std_logic;
    paddle_d3: out std_logic;
    paddle_borrow_out: out std_logic;
    paddle_carry_out: out std_logic;
    x_scan_b0: out std_logic;
    x_scan_b1: out std_logic;
    x_scan_b2: out std_logic;
    x_scan_b3: out std_logic;
    x_scan_b4: out std_logic;
    x_scan_b5: out std_logic;
    x_scan_b6: out std_logic;
    x_scan_b7: out std_logic;
    x_scan_b8: out std_logic;
    x_scan_b9: out std_logic;
    x_scan_gt_4: out std_logic;
    x_scan_eq_4: out std_logic;
    x_scan_lt_4: out std_logic;
    x_scan_gt_6: out std_logic;
    x_scan_eq_6: out std_logic;
    x_scan_lt_6: out std_logic;
    hsync_n: out std_logic;
    x_scan_gt_8: out std_logic;
    x_scan_eq_8: out std_logic;
    x_scan_lt_8: out std_logic;
    x_scan_clear_n: out std_logic;
    y_scan_b0: out std_logic;
    y_scan_b1: out std_logic;
    y_scan_b2: out std_logic;
    y_scan_b3: out std_logic;
    y_scan_b4: out std_logic;
    y_scan_b5: out std_logic;
    y_scan_b6: out std_logic;
    y_scan_b7: out std_logic;
    y_scan_b8: out std_logic;
    y_scan_b9: out std_logic;
    y_scan_gt_4: out std_logic;
    y_scan_eq_4: out std_logic;
    y_scan_lt_4: out std_logic;
    y_scan_gt_6: out std_logic;
    y_scan_eq_6: out std_logic;
    y_scan_lt_6: out std_logic;
    vsync_n: out std_logic;
    y_scan_gt_8: out std_logic;
    y_scan_eq_8: out std_logic;
    y_scan_lt_8: out std_logic;
    y_scan_clear_n: out std_logic;
    x_paddle_px_b0: out std_logic;
    x_paddle_px_b1: out std_logic;
    x_paddle_px_b2: out std_logic;
    x_paddle_px_b3: out std_logic;
    x_paddle_px_b4: out std_logic;
    x_paddle_px_b5: out std_logic;
    x_paddle_px_b6: out std_logic;
    x_paddle_px_b7: out std_logic;
    x_paddle_px_b8: out std_logic;
    x_paddle_px_b9: out std_logic);
end main;

architecture Behavioral of main is
  signal x_paddle_px_b4_temp: std_logic;
  signal x_paddle_px_b3_temp: std_logic;
  signal paddle_d1_temp: std_logic;
  signal paddle_d0_temp: std_logic;
  signal x_scan_clear_n_temp: std_logic;
  signal x_scan_b3_temp: std_logic;
  signal x_scan_b2_temp: std_logic;
  signal x_scan_b1_temp: std_logic;
  signal x_scan_b0_temp: std_logic;
  signal s0: std_logic;
  signal x_scan_b7_temp: std_logic;
  signal x_scan_b6_temp: std_logic;
  signal x_scan_b5_temp: std_logic;
  signal x_scan_b4_temp: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal x_scan_b9_temp: std_logic;
  signal x_scan_b8_temp: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal s15: std_logic;
  signal s16: std_logic;
  signal s17: std_logic;
  signal s18: std_logic;
  signal s19: std_logic;
  signal s20: std_logic;
  signal s21: std_logic;
  signal x_scan_gt_4_temp: std_logic;
  signal s22: std_logic;
  signal s23: std_logic;
  signal s24: std_logic;
  signal const12b4: std_logic_vector(11 downto 0);
  signal s25: std_logic;
  signal s26: std_logic;
  signal s27: std_logic;
  signal s28: std_logic;
  signal s29: std_logic;
  signal s30: std_logic;
  signal s31: std_logic;
  signal s32: std_logic;
  signal s33: std_logic;
  signal s34: std_logic;
  signal s35: std_logic;
  signal s36: std_logic;
  signal s37: std_logic;
  signal s38: std_logic;
  signal s39: std_logic;
  signal s40: std_logic;
  signal s41: std_logic;
  signal s42: std_logic;
  signal x_scan_lt_6_temp: std_logic;
  signal s43: std_logic;
  signal s44: std_logic;
  signal s45: std_logic;
  signal const12b6: std_logic_vector(11 downto 0);
  signal const3b2: std_logic_vector(2 downto 0);
  signal s46: std_logic;
  signal s47: std_logic;
  signal s48: std_logic;
  signal s49: std_logic;
  signal s50: std_logic;
  signal s51: std_logic;
  signal s52: std_logic;
  signal s53: std_logic;
  signal s54: std_logic;
  signal s55: std_logic;
  signal s56: std_logic;
  signal s57: std_logic;
  signal s58: std_logic;
  signal s59: std_logic;
  signal s60: std_logic;
  signal s61: std_logic;
  signal s62: std_logic;
  signal s63: std_logic;
  signal s64: std_logic;
  signal s65: std_logic;
  signal s66: std_logic;
  signal const12b8: std_logic_vector(11 downto 0);
  signal y_scan_clear_n_temp: std_logic;
  signal y_scan_b3_temp: std_logic;
  signal y_scan_b2_temp: std_logic;
  signal y_scan_b1_temp: std_logic;
  signal y_scan_b0_temp: std_logic;
  signal s67: std_logic;
  signal y_scan_b7_temp: std_logic;
  signal y_scan_b6_temp: std_logic;
  signal y_scan_b5_temp: std_logic;
  signal y_scan_b4_temp: std_logic;
  signal s68: std_logic;
  signal s69: std_logic;
  signal s70: std_logic;
  signal y_scan_b9_temp: std_logic;
  signal y_scan_b8_temp: std_logic;
  signal s71: std_logic;
  signal s72: std_logic;
  signal s73: std_logic;
  signal s74: std_logic;
  signal s75: std_logic;
  signal s76: std_logic;
  signal s77: std_logic;
  signal s78: std_logic;
  signal s79: std_logic;
  signal s80: std_logic;
  signal s81: std_logic;
  signal s82: std_logic;
  signal s83: std_logic;
  signal s84: std_logic;
  signal s85: std_logic;
  signal s86: std_logic;
  signal s87: std_logic;
  signal s88: std_logic;
  signal y_scan_gt_4_temp: std_logic;
  signal s89: std_logic;
  signal s90: std_logic;
  signal s91: std_logic;
  signal s92: std_logic;
  signal s93: std_logic;
  signal s94: std_logic;
  signal s95: std_logic;
  signal s96: std_logic;
  signal s97: std_logic;
  signal s98: std_logic;
  signal s99: std_logic;
  signal s100: std_logic;
  signal s101: std_logic;
  signal s102: std_logic;
  signal s103: std_logic;
  signal s104: std_logic;
  signal s105: std_logic;
  signal s106: std_logic;
  signal s107: std_logic;
  signal s108: std_logic;
  signal s109: std_logic;
  signal y_scan_lt_6_temp: std_logic;
  signal s110: std_logic;
  signal s111: std_logic;
  signal s112: std_logic;
  signal s113: std_logic;
  signal s114: std_logic;
  signal s115: std_logic;
  signal s116: std_logic;
  signal s117: std_logic;
  signal s118: std_logic;
  signal s119: std_logic;
  signal s120: std_logic;
  signal s121: std_logic;
  signal s122: std_logic;
  signal s123: std_logic;
  signal s124: std_logic;
  signal s125: std_logic;
  signal s126: std_logic;
  signal s127: std_logic;
  signal s128: std_logic;
  signal s129: std_logic;
  signal s130: std_logic;
  signal s131: std_logic;
  signal s132: std_logic;
  signal s133: std_logic;
  signal x_paddle_px_b2_temp: std_logic;
begin
  const12b4 <= "000000000100";
  const12b6 <= "000000000110";
  const3b2 <= "010";
  const12b8 <= "000000001000";
  x_paddle_px_b2_temp <= '0';
  gate0: entity work.n74193 -- x_paddle_counter
    port map (
      D1 => paddle_load_n,
      DN => paddle_down,
      UP => paddle_up,
      GND => '0',
      D3 => paddle_q3_in,
      D2 => paddle_q2_in,
      notLD => paddle_q1_in,
      CLR => paddle_q0_in,
      D0 => paddle_clear,
      VCC => '1',
      Q1 => x_paddle_px_b4_temp,
      Q0 => x_paddle_px_b3_temp,
      Q2 => paddle_d1_temp,
      Q3 => paddle_d0_temp,
      notCO => paddle_borrow_out,
      notBO => paddle_carry_out);
  s11 <= const12b4(0);
  s12 <= const12b4(1);
  s13 <= const12b4(2);
  s4 <= const12b4(3);
  s18 <= const12b4(4);
  s19 <= const12b4(5);
  s20 <= const12b4(6);
  s14 <= const12b4(7);
  s22 <= const12b4(8);
  s23 <= const12b4(9);
  s24 <= const12b4(10);
  s21 <= const12b4(11);
  s32 <= const12b6(0);
  s33 <= const12b6(1);
  s34 <= const12b6(2);
  s25 <= const12b6(3);
  s39 <= const12b6(4);
  s40 <= const12b6(5);
  s41 <= const12b6(6);
  s35 <= const12b6(7);
  s43 <= const12b6(8);
  s44 <= const12b6(9);
  s45 <= const12b6(10);
  s42 <= const12b6(11);
  s5 <= const3b2(0);
  s6 <= const3b2(1);
  s7 <= const3b2(2);
  s53 <= const12b8(0);
  s54 <= const12b8(1);
  s55 <= const12b8(2);
  s46 <= const12b8(3);
  s60 <= const12b8(4);
  s61 <= const12b8(5);
  s62 <= const12b8(6);
  s56 <= const12b8(7);
  s64 <= const12b8(8);
  s65 <= const12b8(9);
  s66 <= const12b8(10);
  s63 <= const12b8(11);
  gate1: entity work.n74283 -- x_paddle_times_40_adder
    port map (
      B2 => paddle_d0_temp,
      A2 => x_paddle_px_b4_temp,
      A1 => x_paddle_px_b3_temp,
      B1 => paddle_d1_temp,
      C0 => x_paddle_px_b2_temp,
      GND => '0',
      B4 => x_paddle_px_b2_temp,
      A4 => paddle_d0_temp,
      A3 => paddle_d1_temp,
      B3 => x_paddle_px_b2_temp,
      VCC => '1',
      S2 => x_paddle_px_b6,
      S1 => x_paddle_px_b5,
      C4 => x_paddle_px_b9,
      S4 => x_paddle_px_b8,
      S3 => x_paddle_px_b7);
  gate2: entity work.n7485 -- x_scan_cmp4_bits_0_3
    port map (
      Q_3 => s4,
      PleQ_i => s5,
      PeqQ_i => s6,
      PgrQ_i => s7,
      GND => '0',
      Q_0 => s11,
      P_0 => x_scan_b0_temp,
      Q_1 => s12,
      P_1 => x_scan_b1_temp,
      P_2 => x_scan_b2_temp,
      Q_2 => s13,
      P_3 => x_scan_b3_temp,
      VCC => '1',
      PgrQ => s8,
      PeqQ => s9,
      PleQ => s10);
  gate3: entity work.n7485 -- x_scan_cmp4_bits_4_7
    port map (
      Q_3 => s14,
      PleQ_i => s10,
      PeqQ_i => s9,
      PgrQ_i => s8,
      GND => '0',
      Q_0 => s18,
      P_0 => x_scan_b4_temp,
      Q_1 => s19,
      P_1 => x_scan_b5_temp,
      P_2 => x_scan_b6_temp,
      Q_2 => s20,
      P_3 => x_scan_b7_temp,
      VCC => '1',
      PgrQ => s15,
      PeqQ => s16,
      PleQ => s17);
  gate4: entity work.n7485 -- x_scan_cmp4_bits_8_11
    port map (
      Q_3 => s21,
      PleQ_i => s17,
      PeqQ_i => s16,
      PgrQ_i => s15,
      GND => '0',
      Q_0 => s22,
      P_0 => x_scan_b8_temp,
      Q_1 => s23,
      P_1 => x_scan_b9_temp,
      P_2 => s3,
      Q_2 => s24,
      P_3 => s2,
      VCC => '1',
      PgrQ => x_scan_gt_4_temp,
      PeqQ => x_scan_eq_4,
      PleQ => x_scan_lt_4);
  gate5: entity work.n7485 -- x_scan_cmp6_bits_0_3
    port map (
      Q_3 => s25,
      PleQ_i => s26,
      PeqQ_i => s27,
      PgrQ_i => s28,
      GND => '0',
      Q_0 => s32,
      P_0 => x_scan_b0_temp,
      Q_1 => s33,
      P_1 => x_scan_b1_temp,
      P_2 => x_scan_b2_temp,
      Q_2 => s34,
      P_3 => x_scan_b3_temp,
      VCC => '1',
      PgrQ => s29,
      PeqQ => s30,
      PleQ => s31);
  gate6: entity work.n7485 -- x_scan_cmp6_bits_4_7
    port map (
      Q_3 => s35,
      PleQ_i => s31,
      PeqQ_i => s30,
      PgrQ_i => s29,
      GND => '0',
      Q_0 => s39,
      P_0 => x_scan_b4_temp,
      Q_1 => s40,
      P_1 => x_scan_b5_temp,
      P_2 => x_scan_b6_temp,
      Q_2 => s41,
      P_3 => x_scan_b7_temp,
      VCC => '1',
      PgrQ => s36,
      PeqQ => s37,
      PleQ => s38);
  gate7: entity work.n7485 -- x_scan_cmp6_bits_8_11
    port map (
      Q_3 => s42,
      PleQ_i => s38,
      PeqQ_i => s37,
      PgrQ_i => s36,
      GND => '0',
      Q_0 => s43,
      P_0 => x_scan_b8_temp,
      Q_1 => s44,
      P_1 => x_scan_b9_temp,
      P_2 => s3,
      Q_2 => s45,
      P_3 => s2,
      VCC => '1',
      PgrQ => x_scan_gt_6,
      PeqQ => x_scan_eq_6,
      PleQ => x_scan_lt_6_temp);
  gate8: entity work.n7485 -- x_scan_cmp8_bits_0_3
    port map (
      Q_3 => s46,
      PleQ_i => s47,
      PeqQ_i => s48,
      PgrQ_i => s49,
      GND => '0',
      Q_0 => s53,
      P_0 => x_scan_b0_temp,
      Q_1 => s54,
      P_1 => x_scan_b1_temp,
      P_2 => x_scan_b2_temp,
      Q_2 => s55,
      P_3 => x_scan_b3_temp,
      VCC => '1',
      PgrQ => s50,
      PeqQ => s51,
      PleQ => s52);
  gate9: entity work.n7485 -- x_scan_cmp8_bits_4_7
    port map (
      Q_3 => s56,
      PleQ_i => s52,
      PeqQ_i => s51,
      PgrQ_i => s50,
      GND => '0',
      Q_0 => s60,
      P_0 => x_scan_b4_temp,
      Q_1 => s61,
      P_1 => x_scan_b5_temp,
      P_2 => x_scan_b6_temp,
      Q_2 => s62,
      P_3 => x_scan_b7_temp,
      VCC => '1',
      PgrQ => s57,
      PeqQ => s58,
      PleQ => s59);
  gate10: entity work.n7485 -- x_scan_cmp8_bits_8_11
    port map (
      Q_3 => s63,
      PleQ_i => s59,
      PeqQ_i => s58,
      PgrQ_i => s57,
      GND => '0',
      Q_0 => s64,
      P_0 => x_scan_b8_temp,
      Q_1 => s65,
      P_1 => x_scan_b9_temp,
      P_2 => s3,
      Q_2 => s66,
      P_3 => s2,
      VCC => '1',
      PgrQ => x_scan_gt_8,
      PeqQ => x_scan_eq_8,
      PleQ => x_scan_clear_n_temp);
  gate11: entity work.n74163 -- x_scan_counter_bits_0_3
    port map (
      notSR => x_scan_clear_n_temp,
      CP => pixel_clock,
      P0 => '0',
      P1 => '0',
      P2 => '0',
      P3 => '0',
      CEP => '1',
      GND => '0',
      notPE => '1',
      CET => '1',
      VCC => '1',
      Q3 => x_scan_b3_temp,
      Q2 => x_scan_b2_temp,
      Q1 => x_scan_b1_temp,
      Q0 => x_scan_b0_temp,
      TC => s0);
  hsync_n <= NOT (x_scan_gt_4_temp AND x_scan_lt_6_temp);
  gate12: entity work.n74163 -- x_scan_counter_bits_4_7
    port map (
      notSR => x_scan_clear_n_temp,
      CP => pixel_clock,
      P0 => '0',
      P1 => '0',
      P2 => '0',
      P3 => '0',
      CEP => '1',
      GND => '0',
      notPE => '1',
      CET => s0,
      VCC => '1',
      Q3 => x_scan_b7_temp,
      Q2 => x_scan_b6_temp,
      Q1 => x_scan_b5_temp,
      Q0 => x_scan_b4_temp,
      TC => s1);
  gate13: entity work.n74163 -- x_scan_counter_bits_8_11
    port map (
      notSR => x_scan_clear_n_temp,
      CP => pixel_clock,
      P0 => '0',
      P1 => '0',
      P2 => '0',
      P3 => '0',
      CEP => '1',
      GND => '0',
      notPE => '1',
      CET => s1,
      VCC => '1',
      Q3 => s2,
      Q2 => s3,
      Q1 => x_scan_b9_temp,
      Q0 => x_scan_b8_temp);
  gate14: entity work.n74163 -- y_scan_counter_bits_0_3
    port map (
      notSR => y_scan_clear_n_temp,
      CP => x_scan_clear_n_temp,
      P0 => '0',
      P1 => '0',
      P2 => '0',
      P3 => '0',
      CEP => '1',
      GND => '0',
      notPE => '1',
      CET => '1',
      VCC => '1',
      Q3 => y_scan_b3_temp,
      Q2 => y_scan_b2_temp,
      Q1 => y_scan_b1_temp,
      Q0 => y_scan_b0_temp,
      TC => s67);
  gate15: entity work.n74163 -- y_scan_counter_bits_4_7
    port map (
      notSR => y_scan_clear_n_temp,
      CP => x_scan_clear_n_temp,
      P0 => '0',
      P1 => '0',
      P2 => '0',
      P3 => '0',
      CEP => '1',
      GND => '0',
      notPE => '1',
      CET => s67,
      VCC => '1',
      Q3 => y_scan_b7_temp,
      Q2 => y_scan_b6_temp,
      Q1 => y_scan_b5_temp,
      Q0 => y_scan_b4_temp,
      TC => s68);
  gate16: entity work.n74163 -- y_scan_counter_bits_8_11
    port map (
      notSR => y_scan_clear_n_temp,
      CP => x_scan_clear_n_temp,
      P0 => '0',
      P1 => '0',
      P2 => '0',
      P3 => '0',
      CEP => '1',
      GND => '0',
      notPE => '1',
      CET => s68,
      VCC => '1',
      Q3 => s69,
      Q2 => s70,
      Q1 => y_scan_b9_temp,
      Q0 => y_scan_b8_temp);
  gate17: entity work.n7485 -- y_scan_cmp4_bits_0_3
    port map (
      Q_3 => s71,
      PleQ_i => s72,
      PeqQ_i => s73,
      PgrQ_i => s74,
      GND => '0',
      Q_0 => s78,
      P_0 => y_scan_b0_temp,
      Q_1 => s79,
      P_1 => y_scan_b1_temp,
      P_2 => y_scan_b2_temp,
      Q_2 => s80,
      P_3 => y_scan_b3_temp,
      VCC => '1',
      PgrQ => s75,
      PeqQ => s76,
      PleQ => s77);
  gate18: entity work.n7485 -- y_scan_cmp4_bits_4_7
    port map (
      Q_3 => s81,
      PleQ_i => s77,
      PeqQ_i => s76,
      PgrQ_i => s75,
      GND => '0',
      Q_0 => s85,
      P_0 => y_scan_b4_temp,
      Q_1 => s86,
      P_1 => y_scan_b5_temp,
      P_2 => y_scan_b6_temp,
      Q_2 => s87,
      P_3 => y_scan_b7_temp,
      VCC => '1',
      PgrQ => s82,
      PeqQ => s83,
      PleQ => s84);
  gate19: entity work.n7485 -- y_scan_cmp4_bits_8_11
    port map (
      Q_3 => s88,
      PleQ_i => s84,
      PeqQ_i => s83,
      PgrQ_i => s82,
      GND => '0',
      Q_0 => s89,
      P_0 => y_scan_b8_temp,
      Q_1 => s90,
      P_1 => y_scan_b9_temp,
      P_2 => s70,
      Q_2 => s91,
      P_3 => s69,
      VCC => '1',
      PgrQ => y_scan_gt_4_temp,
      PeqQ => y_scan_eq_4,
      PleQ => y_scan_lt_4);
  gate20: entity work.n7485 -- y_scan_cmp6_bits_0_3
    port map (
      Q_3 => s92,
      PleQ_i => s93,
      PeqQ_i => s94,
      PgrQ_i => s95,
      GND => '0',
      Q_0 => s99,
      P_0 => y_scan_b0_temp,
      Q_1 => s100,
      P_1 => y_scan_b1_temp,
      P_2 => y_scan_b2_temp,
      Q_2 => s101,
      P_3 => y_scan_b3_temp,
      VCC => '1',
      PgrQ => s96,
      PeqQ => s97,
      PleQ => s98);
  gate21: entity work.n7485 -- y_scan_cmp6_bits_4_7
    port map (
      Q_3 => s102,
      PleQ_i => s98,
      PeqQ_i => s97,
      PgrQ_i => s96,
      GND => '0',
      Q_0 => s106,
      P_0 => y_scan_b4_temp,
      Q_1 => s107,
      P_1 => y_scan_b5_temp,
      P_2 => y_scan_b6_temp,
      Q_2 => s108,
      P_3 => y_scan_b7_temp,
      VCC => '1',
      PgrQ => s103,
      PeqQ => s104,
      PleQ => s105);
  gate22: entity work.n7485 -- y_scan_cmp6_bits_8_11
    port map (
      Q_3 => s109,
      PleQ_i => s105,
      PeqQ_i => s104,
      PgrQ_i => s103,
      GND => '0',
      Q_0 => s110,
      P_0 => y_scan_b8_temp,
      Q_1 => s111,
      P_1 => y_scan_b9_temp,
      P_2 => s70,
      Q_2 => s112,
      P_3 => s69,
      VCC => '1',
      PgrQ => y_scan_gt_6,
      PeqQ => y_scan_eq_6,
      PleQ => y_scan_lt_6_temp);
  gate23: entity work.n7485 -- y_scan_cmp8_bits_0_3
    port map (
      Q_3 => s113,
      PleQ_i => s114,
      PeqQ_i => s115,
      PgrQ_i => s116,
      GND => '0',
      Q_0 => s120,
      P_0 => y_scan_b0_temp,
      Q_1 => s121,
      P_1 => y_scan_b1_temp,
      P_2 => y_scan_b2_temp,
      Q_2 => s122,
      P_3 => y_scan_b3_temp,
      VCC => '1',
      PgrQ => s117,
      PeqQ => s118,
      PleQ => s119);
  gate24: entity work.n7485 -- y_scan_cmp8_bits_4_7
    port map (
      Q_3 => s123,
      PleQ_i => s119,
      PeqQ_i => s118,
      PgrQ_i => s117,
      GND => '0',
      Q_0 => s127,
      P_0 => y_scan_b4_temp,
      Q_1 => s128,
      P_1 => y_scan_b5_temp,
      P_2 => y_scan_b6_temp,
      Q_2 => s129,
      P_3 => y_scan_b7_temp,
      VCC => '1',
      PgrQ => s124,
      PeqQ => s125,
      PleQ => s126);
  gate25: entity work.n7485 -- y_scan_cmp8_bits_8_11
    port map (
      Q_3 => s130,
      PleQ_i => s126,
      PeqQ_i => s125,
      PgrQ_i => s124,
      GND => '0',
      Q_0 => s131,
      P_0 => y_scan_b8_temp,
      Q_1 => s132,
      P_1 => y_scan_b9_temp,
      P_2 => s70,
      Q_2 => s133,
      P_3 => s69,
      VCC => '1',
      PgrQ => y_scan_gt_8,
      PeqQ => y_scan_eq_8,
      PleQ => y_scan_clear_n_temp);
  vsync_n <= NOT (y_scan_gt_4_temp AND y_scan_lt_6_temp);
  s26 <= null(0);
  s27 <= null(1);
  s28 <= null(2);
  s47 <= null(0);
  s48 <= null(1);
  s49 <= null(2);
  s78 <= null(0);
  s79 <= null(1);
  s80 <= null(2);
  s71 <= null(3);
  s85 <= null(4);
  s86 <= null(5);
  s87 <= null(6);
  s81 <= null(7);
  s89 <= null(8);
  s90 <= null(9);
  s91 <= null(10);
  s88 <= null(11);
  s99 <= null(0);
  s100 <= null(1);
  s101 <= null(2);
  s92 <= null(3);
  s106 <= null(4);
  s107 <= null(5);
  s108 <= null(6);
  s102 <= null(7);
  s110 <= null(8);
  s111 <= null(9);
  s112 <= null(10);
  s109 <= null(11);
  s72 <= null(0);
  s73 <= null(1);
  s74 <= null(2);
  s93 <= null(0);
  s94 <= null(1);
  s95 <= null(2);
  s120 <= null(0);
  s121 <= null(1);
  s122 <= null(2);
  s113 <= null(3);
  s127 <= null(4);
  s128 <= null(5);
  s129 <= null(6);
  s123 <= null(7);
  s131 <= null(8);
  s132 <= null(9);
  s133 <= null(10);
  s130 <= null(11);
  s114 <= null(0);
  s115 <= null(1);
  s116 <= null(2);
  paddle_d0 <= paddle_d0_temp;
  paddle_d1 <= paddle_d1_temp;
  paddle_d2 <= x_paddle_px_b4_temp;
  paddle_d3 <= x_paddle_px_b3_temp;
  x_scan_b0 <= x_scan_b0_temp;
  x_scan_b1 <= x_scan_b1_temp;
  x_scan_b2 <= x_scan_b2_temp;
  x_scan_b3 <= x_scan_b3_temp;
  x_scan_b4 <= x_scan_b4_temp;
  x_scan_b5 <= x_scan_b5_temp;
  x_scan_b6 <= x_scan_b6_temp;
  x_scan_b7 <= x_scan_b7_temp;
  x_scan_b8 <= x_scan_b8_temp;
  x_scan_b9 <= x_scan_b9_temp;
  x_scan_gt_4 <= x_scan_gt_4_temp;
  x_scan_lt_6 <= x_scan_lt_6_temp;
  x_scan_lt_8 <= x_scan_clear_n_temp;
  x_scan_clear_n <= x_scan_clear_n_temp;
  y_scan_b0 <= y_scan_b0_temp;
  y_scan_b1 <= y_scan_b1_temp;
  y_scan_b2 <= y_scan_b2_temp;
  y_scan_b3 <= y_scan_b3_temp;
  y_scan_b4 <= y_scan_b4_temp;
  y_scan_b5 <= y_scan_b5_temp;
  y_scan_b6 <= y_scan_b6_temp;
  y_scan_b7 <= y_scan_b7_temp;
  y_scan_b8 <= y_scan_b8_temp;
  y_scan_b9 <= y_scan_b9_temp;
  y_scan_gt_4 <= y_scan_gt_4_temp;
  y_scan_lt_6 <= y_scan_lt_6_temp;
  y_scan_lt_8 <= y_scan_clear_n_temp;
  y_scan_clear_n <= y_scan_clear_n_temp;
  x_paddle_px_b0 <= x_paddle_px_b2_temp;
  x_paddle_px_b1 <= x_paddle_px_b2_temp;
  x_paddle_px_b2 <= x_paddle_px_b2_temp;
  x_paddle_px_b3 <= x_paddle_px_b3_temp;
  x_paddle_px_b4 <= x_paddle_px_b4_temp;
end Behavioral;
