-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity DIG_JK_FF_AS is
  generic (Default : std_logic);  
  port (
    Q: out std_logic;
    notQ: out std_logic;
    Set: in std_logic;
    J: in std_logic;
    C: in std_logic;
    K: in std_logic;
    Clr: in std_logic );
end DIG_JK_FF_AS;

architecture Behavioral of DIG_JK_FF_AS is
  signal state: std_logic := Default;
begin
    process (C, Clr, Set)
    begin
        if (Set='1') then
            state <= '1';
        elsif (Clr='1') then
            state <= '0';
        elsif rising_edge(C) then
          if (J='0' and K='1') then
             state <= '0';
          elsif (J='1' and K='0') then
             state <= '1';
          elsif (J='1' and K='1') then
             state <= not (state);
          end if;
        end if;
    end process;

    Q <= state;
    notQ <= NOT( state );
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

-- Synchronous 4-Bit Up/Down Binary Counter with Dual Clock
entity n74193 is
  port (
    DN: in std_logic; -- Down Count
    UP: in std_logic; -- Up Count
    D0: in std_logic; -- Data Input 0
    D1: in std_logic; -- Data Input 1
    D2: in std_logic; -- Data Input 2
    D3: in std_logic; -- Data Input 3
    CLR: in std_logic; -- Clear
    notLD: in std_logic; -- Load
    VCC: in std_logic;
    GND: in std_logic;
    notBO: out std_logic; -- Borrow Output
    notCO: out std_logic; -- Carry Output
    Q0: out std_logic; -- Output Q0
    Q1: out std_logic; -- Output Q1
    Q2: out std_logic; -- Output Q2
    Q3: out std_logic -- Output Q3
    );
end n74193;

architecture Behavioral of n74193 is
  signal Q0_temp: std_logic;
  signal Q1_temp: std_logic;
  signal Q2_temp: std_logic;
  signal Q3_temp: std_logic;
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal s15: std_logic;
  signal s16: std_logic;
  signal s17: std_logic;
  signal s18: std_logic;
  signal s19: std_logic;
  signal s20: std_logic;
  signal s21: std_logic;
  signal s22: std_logic;
  signal s23: std_logic;
begin
  s1 <= NOT DN;
  s0 <= NOT UP;
  s7 <= NOT CLR;
  s6 <= NOT notLD;
  s8 <= NOT (D0 AND s6 AND s7);
  s11 <= NOT (s1 OR s0);
  s12 <= NOT (D1 AND s6 AND s7);
  s16 <= NOT (D2 AND s6 AND s7);
  s20 <= NOT (D3 AND s6 AND s7);
  s9 <= (NOT s7 OR NOT (NOT (s8 AND s6)));
  s10 <= NOT s8;
  s13 <= (NOT s7 OR NOT (NOT (s12 AND s6)));
  s14 <= NOT s12;
  s17 <= (NOT s7 OR NOT (NOT (s16 AND s6)));
  s18 <= NOT s16;
  s21 <= (NOT s7 OR NOT (NOT (s20 AND s6)));
  s22 <= NOT s20;
  gate0: entity work.DIG_JK_FF_AS
    generic map (
      Default => '0')
    port map (
      Set => s10,
      J => '1',
      C => s11,
      K => '1',
      Clr => s9,
      Q => Q0_temp,
      notQ => s2);
  s15 <= NOT ((s1 AND s2) OR (Q0_temp AND s0));
  gate1: entity work.DIG_JK_FF_AS
    generic map (
      Default => '0')
    port map (
      Set => s14,
      J => '1',
      C => s15,
      K => '1',
      Clr => s13,
      Q => Q1_temp,
      notQ => s3);
  s19 <= NOT ((s1 AND s2 AND s3) OR (Q0_temp AND Q1_temp AND s0));
  gate2: entity work.DIG_JK_FF_AS
    generic map (
      Default => '0')
    port map (
      Set => s18,
      J => '1',
      C => s19,
      K => '1',
      Clr => s17,
      Q => Q2_temp,
      notQ => s4);
  s23 <= NOT ((s1 AND s2 AND s3 AND s4) OR (Q0_temp AND Q1_temp AND Q2_temp AND s0));
  gate3: entity work.DIG_JK_FF_AS
    generic map (
      Default => '0')
    port map (
      Set => s22,
      J => '1',
      C => s23,
      K => '1',
      Clr => s21,
      Q => Q3_temp,
      notQ => s5);
  notCO <= NOT (Q0_temp AND Q1_temp AND Q2_temp AND Q3_temp AND s0);
  notBO <= NOT (s1 AND s2 AND s3 AND s4 AND s5);
  Q0 <= Q0_temp;
  Q1 <= Q1_temp;
  Q2 <= Q2_temp;
  Q3 <= Q3_temp;
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_BUS_1 is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic;
    
    in_0: in std_logic_vector ((Bits-1) downto 0);
    in_1: in std_logic_vector ((Bits-1) downto 0) );
end MUX_GATE_BUS_1;

architecture Behavioral of MUX_GATE_BUS_1 is
begin
  with sel select
    p_out <=
      in_0 when '0',
      in_1 when '1',
      (others => '0') when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
use ieee.numeric_std.all;
entity DIG_D_FF_BUS is
  generic (
    Default: integer; 
    Bits: integer );
  port ( D  : in std_logic_vector ((Bits-1) downto 0);
         C  : in std_logic;
         Q  : out std_logic_vector ((Bits-1) downto 0);
         notQ : out std_logic_vector ((Bits-1) downto 0) );
end DIG_D_FF_BUS;

architecture Behavioral of DIG_D_FF_BUS is
   signal state : std_logic_vector ((Bits-1) downto 0) := std_logic_vector(to_unsigned(Default, Bits));
begin
   Q    <= state;
   notQ <= NOT( state );

   process(C)
   begin
      if rising_edge(C) then
        state  <= D;
      end if;
   end process;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;

entity DIG_Add is
  generic ( Bits: integer ); 
  port (
    s: out std_logic_vector((Bits-1) downto 0);
    c_o: out std_logic;
    a: in std_logic_vector((Bits-1) downto 0);
    b: in std_logic_vector((Bits-1) downto 0);
    c_i: in std_logic );
end DIG_Add;

architecture Behavioral of DIG_Add is
   signal temp : std_logic_vector(Bits downto 0);
begin
   temp <= ('0' & a) + b + c_i;

   s    <= temp((Bits-1) downto 0);
   c_o  <= temp(Bits);
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

-- hex synchronous counter
entity n74163 is
  port (
    notPE: in std_logic;
    notSR: in std_logic;
    CP: in std_logic;
    CET: in std_logic;
    CEP: in std_logic;
    P0: in std_logic;
    P1: in std_logic;
    P2: in std_logic;
    P3: in std_logic;
    VCC: in std_logic;
    GND: in std_logic;
    TC: out std_logic;
    Q0: out std_logic;
    Q1: out std_logic;
    Q2: out std_logic;
    Q3: out std_logic);
end n74163;

architecture Behavioral of n74163 is
  signal s0: std_logic_vector(3 downto 0);
  signal s1: std_logic_vector(3 downto 0);
  signal s2: std_logic_vector(3 downto 0);
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic_vector(3 downto 0);
  signal s6: std_logic_vector(3 downto 0);
  signal s7: std_logic_vector(3 downto 0);
begin
  s4 <= (CEP AND CET);
  s6(0) <= P0;
  s6(1) <= P1;
  s6(2) <= P2;
  s6(3) <= P3;
  gate0: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 4)
    port map (
      sel => s4,
      in_0 => s1,
      in_1 => s2,
      p_out => s5);
  TC <= (s3 AND CET);
  gate1: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 4)
    port map (
      sel => notPE,
      in_0 => s6,
      in_1 => s5,
      p_out => s7);
  gate2: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 4)
    port map (
      sel => notSR,
      in_0 => "0000",
      in_1 => s7,
      p_out => s0);
  gate3: entity work.DIG_D_FF_BUS -- Q
    generic map (
      Default => 0,
      Bits => 4)
    port map (
      D => s0,
      C => CP,
      Q => s1);
  gate4: entity work.DIG_Add
    generic map (
      Bits => 4)
    port map (
      a => s1,
      b => "0001",
      c_i => '0',
      s => s2,
      c_o => s3);
  Q0 <= s1(0);
  Q1 <= s1(1);
  Q2 <= s1(2);
  Q3 <= s1(3);
end Behavioral;
